"""
JARVIS Fine-Tuning — Step 2: LoRA Fine-Tuning with MLX
=======================================================
Runs LoRA fine-tuning on Apple Silicon using Apple's MLX framework.
Uses the training data generated by generate_training_data.py.

Requirements:
  pip install mlx-lm huggingface_hub

Usage:
  python finetune.py                    # uses defaults
  python finetune.py --iters 300        # more training steps
  python finetune.py --ram 8            # optimise for 8GB RAM Mac
  python finetune.py --ram 16           # optimise for 16GB RAM Mac

Output:
  adapters/   ← LoRA adapter weights (small, ~50-200MB)

This script DOES NOT modify the base llama3.2:3b model.
The adapter is a separate file that layers on top of it.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys

HERE         = os.path.dirname(os.path.abspath(__file__))
DATA_DIR     = os.path.join(HERE, "finetune_data")
ADAPTER_DIR  = os.path.join(HERE, "adapters")
BASE_MODEL   = "mlx-community/Llama-3.2-3B-Instruct-4bit"   # ~2.2GB download


def check_prerequisites():
    """Verify mlx-lm is installed and training data exists."""
    try:
        import mlx_lm
        print(f"✓ mlx-lm {mlx_lm.__version__} found")
    except ImportError:
        print("✗ mlx-lm not installed. Run:")
        print("    pip install mlx-lm huggingface_hub")
        sys.exit(1)

    train_file = os.path.join(DATA_DIR, "train.jsonl")
    valid_file = os.path.join(DATA_DIR, "valid.jsonl")
    if not os.path.exists(train_file):
        print(f"✗ Training data not found at {train_file}")
        print("  Run generate_training_data.py first")
        sys.exit(1)

    with open(train_file) as f:
        n_train = sum(1 for _ in f)
    with open(valid_file) as f:
        n_valid = sum(1 for _ in f)

    print(f"✓ Training data: {n_train} train / {n_valid} validation examples")
    return n_train


def build_command(args, n_train: int) -> list[str]:
    """Build the mlx_lm.lora training command."""

    # Choose batch size and LoRA layers based on available RAM
    if args.ram >= 16:
        batch_size  = 2
        lora_layers = 16
        print("📊 Config: 16GB+ RAM → batch_size=2, lora_layers=16")
    else:
        batch_size  = 1    # smaller batches = more stable with 558 examples
        lora_layers = 8
        print("📊 Config: 8GB RAM → batch_size=1, lora_layers=8 (stable mode)")

    # Auto-calculate reasonable number of iterations
    # Rule of thumb: ~3-5 passes through the dataset
    iters = args.iters or min(max(n_train * 1, 200), 400)   # 558 examples: 300-400 iters is enough
    print(f"📊 Training for {iters} iterations")

    cmd = [
        sys.executable, "-m", "mlx_lm", "lora",
        "--model",           BASE_MODEL,
        "--train",
        "--data",            DATA_DIR,
        "--adapter-path",    ADAPTER_DIR,
        "--iters",           str(iters),
        "--batch-size",      str(batch_size),
        "--num-layers",      str(lora_layers),
        "--learning-rate",   "5e-5",   # lowered from 2e-4 — prevents gradient explosion
        "--steps-per-eval",  "25",
        "--val-batches",     "5",
        "--save-every",      "50",
        "--optimizer",       "adamw",  # weight decay regularisation
        "--max-seq-length",  "1024",
    ]
    return cmd


def main():
    parser = argparse.ArgumentParser(description="Fine-tune Llama 3.2 3B with LoRA on Mac")
    parser.add_argument("--iters",    type=int, default=None,
                        help="Training iterations (default: auto based on dataset size)")
    parser.add_argument("--ram",      type=int, default=8,
                        choices=[8, 16, 24, 32],
                        help="Your Mac's RAM in GB — affects batch size and LoRA layers")
    args = parser.parse_args()

    print(f"\n{'='*56}")
    print(f"  JARVIS LoRA Fine-Tuning")
    print(f"  Base model : {BASE_MODEL}")
    print(f"  Data       : {DATA_DIR}")
    print(f"  Adapters   : {ADAPTER_DIR}")
    print(f"{'='*56}\n")

    n_train = check_prerequisites()
    os.makedirs(ADAPTER_DIR, exist_ok=True)

    cmd = build_command(args, n_train)

    print(f"\n🚀 Starting training...")
    print(f"   Command: {' '.join(cmd[2:])}\n")  # skip 'python -m'

    # First run: download model if needed
    print("📥 Model will be downloaded from HuggingFace if not cached (~2.2GB)")
    print("   This is a one-time download.\n")

    try:
        result = subprocess.run(cmd, cwd=HERE)
        if result.returncode == 0:
            print(f"\n{'='*56}")
            print(f"  ✓ Fine-tuning complete!")
            print(f"  Adapters saved to: {ADAPTER_DIR}")
            print(f"\n  Next step:")
            print(f"    python export_to_ollama.py")
            print(f"{'='*56}\n")
        else:
            print(f"\n✗ Training failed with return code {result.returncode}")
            sys.exit(result.returncode)
    except KeyboardInterrupt:
        print("\n\nTraining interrupted. Partial adapters may be saved.")
        print("You can resume by re-running — MLX saves checkpoints every 50 steps.")


if __name__ == "__main__":
    main()
